### ISSUE TITLE
cant take input

### ISSUE THREAD

**Issue by Tank1334** [raspberrypi/pico-micropython-examples#10]
on the example `blink` if i try taking input it freaks out. i have to completly restart it each time.

**Comment by aallan** [comment]
Sorry, I don't really understand what you're trying to do here, or the problem you are seeing? The blink program 

```
from machine import Pin, Timer

led = Pin(25, Pin.OUT)
tim = Timer()
def tick(timer):
    global led
    led.toggle()

tim.init(freq=2.5, mode=Timer.PERIODIC, callback=tick)
```

blinks the on-board LED on and off, there is nothing to input?

**Comment by Tank1334** [comment]
if i was to do something like:
`from machine import Pin, Timer

led = Pin(25, Pin.OUT)
tim = Timer()
def tick(timer):
    global led
    led.toggle()
    input("TEST")

tim.init(freq=2.5, mode=Timer.PERIODIC, callback=tick)
`
it will return error

**Comment by aallan** [comment]
Hey, this sounds like a general MicroPython support question rather than a question specifically about the example code in this repo. I'm going to direct you over to the https://github.com/micropython/micropython/issues repo as the RP2040 port has now been merged into the upstream repo.
