### ISSUE TITLE
Can not transfer bmp or jpg files to pico wiht Thonny

### ISSUE THREAD

**Issue by CaptainJackey** [raspberrypi/pico-micropython-examples#12]
There are 2 questions:
1、Why pico didn't have a u disk so that can transfer files easily ?
2、Thonney ide only can transfer py files to pico , how can I transfer some files like bmp、jpg ?

**Comment by aallan** [comment]
The first question needs to be be [directed to the MicroPython developers](https://github.com/micropython/micropython), as the RP2040 port of MicroPython has now been merged into the upstream repo,  see micropython/micropython#6791.

Your second question needs to be [directed to the Thonny developers ](https://github.com/thonny/thonny).

**Comment by WarPromo** [comment]
Thanks aallan for the useful / informative response.
