### ISSUE TITLE
Request Deep Sleep example

### ISSUE THREAD

**Issue by vslinuxdotnet** [raspberrypi/pico-micropython-examples#16]
Will be nice to include a Deep Sleep Example:

- Time Interval
-  Interrupt Button
- Changing clock speed at run-time.
- 
Thank you.

**Comment by aallan** [comment]
The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791, and while we're happy to support the MicroPython team with anything they need it's unlikely we'll be adding more MicroPython examples ourselves. I'd encourage you to [open an issue](https://github.com/micropython/micropython/issues) on the MicroPython repo to ask for more example code and documentation to support the RP2040 port.
