### ISSUE TITLE
In wiring for pio/neopixel_ring example, Ring V+ may better be connected to Pico VBUS (pin 40)

### ISSUE THREAD

**Issue by vjou** [raspberrypi/pico-micropython-examples#2]
In pio/neopixel_ring example, 3V3 (pin 36) may be a little low for NeoPixel's V+ as 4-7V is recommended in https://www.adafruit.com/product/1463#description. Unless there is a reason of using 3V3, VBUS (pin 40) may be better for that.

**Comment by aallan** [comment]
Fixed in commit be3ade491b649de3d12121d682fcda17e0699e73

**Comment by aallan** [comment]
This will get pulled into the PDF documentation on the next release. Many thanks.

**Comment by mintakka** [comment]
For larger arrays of pixels, 3.3v may be too low. For the 16 pixel ring in the example, 3.3v is perfectly fine.

**Comment by aallan** [comment]
Documentation has been updated to use VBUS.
