### ISSUE TITLE
timeout function in UART not available

### ISSUE THREAD

**Issue by nayanagg** [raspberrypi/pico-micropython-examples#24]
HI,

I want to use timeout method in UART for Pi Pico.

HELP!

**Comment by aallan** [comment]
Hey, this is a general MicroPython question, not specific to the example code provided in this repo.

The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791. Going forward you should report problems with the port  there, https://github.com/micropython/micropython/. 

General technical support can be found on the MicroPython forums, https://forum.micropython.org/viewforum.php?f=21.

**Comment by dpgeorge** [comment]
FYI there is now support for UART timeouts in MicroPython RPi pico.
