### ISSUE TITLE
DMA and Interrupt examples

### ISSUE THREAD

**Issue by controllerstech** [raspberrypi/pico-micropython-examples#25]
Are there any examples for ADC with DMA or interrupt using the micropython ?
The same goes for Other peripherals too. I can't seem to find any documentation for using DMA or interrupt with either of the peripherals

**Comment by aallan** [comment]
The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791, and while we're happy to support the MicroPython team with anything they need it's unlikely we'll be adding more MicroPython examples ourselves. I'd encourage you to [open an issue](https://github.com/micropython/micropython/issues) on the MicroPython repo to ask for more example code and documentation to support the RP2040 port.
