### ISSUE TITLE
support for UART rx interrupt 

### ISSUE THREAD

**Issue by embhobbb** [raspberrypi/pico-micropython-examples#37]
I am using raspberry pi pico for my new project.
I was checking for example for UART receive interrupt. Do we have support for the same?
How can we achieve the UART rx interrupt.
I checked the micropython documentation but I didn't see support for RPi pico.

**Comment by lurch** [comment]
> I was checking for example for UART receive interrupt. Do we have support for the same?
How can we achieve the UART rx interrupt.

That's probably a question to ask at https://github.com/micropython/micropython/issues or https://forum.micropython.org/

> I checked the micropython documentation but I didn't see support for RPi pico.

Yeah, it's a shame that https://github.com/micropython/micropython/issues/6855 is still open.
