### ISSUE TITLE
PWM Fade additional example for NeoPixels

### ISSUE THREAD

**Issue by mytechnotalent** [raspberrypi/pico-micropython-examples#38]
@kilograham do you have or will you be creating a PWM Fade example for an n-length NeoPixel array?  I see your example https://github.com/raspberrypi/pico-micropython-examples/blob/master/pio/pio_pwm.py which covered a standard LED however would love one that opens this to the NeoPixel.

**Comment by aallan** [comment]
The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791, and while we're happy to support the MicroPython team with anything they need it's unlikely we'll be adding more MicroPython examples ourselves. I'd encourage you to [open an issue](https://github.com/micropython/micropython/issues) on the MicroPython repo to ask for more example code and documentation to support the RP2040 port.
