### ISSUE TITLE
SPI master slave communication

### ISSUE THREAD

**Issue by embhobbb** [raspberrypi/pico-micropython-examples#39]
I am using pico in my project in which I am in need of using master-slave SPI communication.
What modifications are required to change the SPI master code to spi slave?
Is there any existing example for reference.

**Comment by lurch** [comment]
See https://github.com/raspberrypi/pico-micropython-examples/issues/38#issuecomment-859865569

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue.
