### ISSUE TITLE
pio_pinchange.py example pin change to high

### ISSUE THREAD

**Issue by beyonlo** [raspberrypi/pico-micropython-examples#45]
Hi all

I have this function below from this PIO example https://github.com/raspberrypi/pico-micropython-examples/blob/master/pio/pio_pinchange.py 

```
@rp2.asm_pio()
def wait_pin_low():
    wrap_target()

    wait(0, pin, 0)
    irq(block, rel(0))
    wait(1, pin, 0)

    wrap()

```
That example (pio_pinchange.py ) using PIO wait for a pin change to `LOW` and raise an IRQ. I would like to do exactly that, but with pin change do `HIGH`. I readed this doc https://docs.micropython.org/en/latest/library/rp2.html about the commands of PIO to understand a bit, and changed to that code to this:

```
@rp2.asm_pio()
def wait_pin_high():
    wrap_target()

    wait(1, pin, 0)
    irq(block, rel(0))
    wait(0, pin, 0)

    wrap()

```
But not works. I did others modifications, but not success.

Could you please provide this function to works to pin change to high?

I'm using RPICO with MicroPython version 1.8:

```
import os
>>> os.uname()
(sysname='rp2', nodename='rp2', release='1.18.0', version='v1.18 on 2022-01-17 (GNU 11.2.0 MinSizeRel)', machine='Raspberry Pi Pico with RP2040')
>>>

```
Thank you very much!

**Comment by aallan** [comment]
The RP2040 MicroPython port has been merged upstream to the main MicroPython repo, see https://github.com/micropython/micropython/pull/6791. So going forward you should report problems with the port there, https://github.com/micropython/micropython/. Technical support can be found on the MicroPython forums, https://forum.micropython.org/viewforum.php?f=21.
