### ISSUE TITLE
Why can not use IRQ in a new thread?

### ISSUE THREAD

**Issue by jie-smile** [raspberrypi/pico-micropython-examples#47]
```
from machine import Pin
import utime
import _thread

interruptCounter = 0
def callback(pin):
  global interruptCounter
  interruptCounter = interruptCounter+1
  
def foo():
    p16 = Pin(16, Pin.IN, Pin.PULL_UP)
    p16.irq(callback, Pin.IRQ_FALLING)
    while True:
        utime.sleep(1)
        

_thread.start_new_thread(foo, ())

while True:
    print(interruptCounter)
    utime.sleep(1)

```
The irq is not work

**Comment by lurch** [comment]
The RP2040 MicroPython port has been merged upstream to the main MicroPython repo, see https://github.com/micropython/micropython/pull/6791. So going forward you should report problems with the port there, https://github.com/micropython/micropython/. Technical support can be found on the MicroPython forums, https://forum.micropython.org/viewforum.php?f=21.
