### ISSUE TITLE
blink.py doesn't work on Pico W

### ISSUE THREAD

**Issue by henley-regatta** [raspberrypi/pico-micropython-examples#48]
The onboard LED is not tied to GPIO 25 on the new Pico W so the example code in blink.py doesn't work.

Replacing the initialisation with:
     led = Pin("LED", Pin.OUT)

..works using an alias and is portable (for recent firmwares) between Pico and Pico W

**Comment by ph2lb** [comment]
See section 3.4 :  https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf

 led = machine.Pin("LED", machine.Pin.OUT)
