### ISSUE TITLE
require to generate frquency of 1Mhz or above by using clkout 

### ISSUE THREAD

**Issue by gurusar** [raspberrypi/pico-micropython-examples#50]
i have got the code .c file for generating clkout on gpio pins using internal system frequency with a divider. please if can share any document or code regarding this topic in thonny

**Comment by lurch** [comment]
This is a question you'll need to ask at https://github.com/orgs/micropython/discussions

**Comment by dpgeorge** [comment]
Discussion link https://github.com/micropython/micropython/discussions/9269
