### ISSUE TITLE
Pico W i2c issues

### ISSUE THREAD

**Issue by dbuggz** [raspberrypi/pico-micropython-examples#51]
I've had issues with a Pico W running latest MicroPython uf2
`MicroPython v1.19.1 on 2022-09-20; Raspberry Pi Pico W with RP2040`

Running 'i2c.py' 
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
OSError: [Errno 5] EIO
```
same for a couple of different i2c devices.

**Comment by lurch** [comment]
You'll be better off asking for help at https://github.com/orgs/micropython/discussions as that's where MicroPython is actively developed.

**Comment by dbuggz** [comment]
Thanks Andrew,
I found that CircuitPython handled the error more explicitly and adding the bus termination resistors solved the problem.
Dave
