### ISSUE TITLE
Find & Replaced RP2040 to RP2350?

### ISSUE THREAD

**Issue by errolt** [raspberrypi/pico-micropython-examples#75]
There is a confusing issue in the book that might have been caused by a find/replace?

For all PWM code that controls the led there is this note, page 17 and page 26:
> This example does not work with Raspberry Pi Pico W as the on-board LED is connected via the 43439 wireless chip
rather than directly to the **RP2350** itself. The example will work with an off board LED connected to via GPIO.

The Pico W does doesn't use the RP2350, but the RP2040.

**Comment by JamesH65** [comment]
Good spot, will fix for next release.
