### ISSUE TITLE
Raspberry Pi Pico ADC changes the sampling rate in Free-running Sampling mode

### ISSUE THREAD

**Issue by leezisheng** [raspberrypi/pico-micropython-examples#79]
I am configuring the ADC sampling rate here. Due to unknown reasons, the DIV register cannot be configured here. The actual sampling period is fixed at 65.
Can anyone help me what is going wrong here？
<img width="551" alt="c39121a7385513c1579481977b0c62e" src="https://github.com/user-attachments/assets/5fb8eb58-d244-40c1-9607-16754808558c">
<img width="512" alt="b078a23843d708c1ae0b4c6966c8a88" src="https://github.com/user-attachments/assets/fe217690-835d-42d3-94e9-2bcbf0fc4925">
<img width="554" alt="a91a38f1944c012e122d14c44dcbc40" src="https://github.com/user-attachments/assets/9ffe2d0c-c3c5-4526-9309-010c16cedf99">

**Comment by leezisheng** [comment]
<img width="590" alt="797da40d11893393b23f0094028ae9f" src="https://github.com/user-attachments/assets/ba1d607d-e036-4021-b34d-c58a802f624b">

**Comment by leezisheng** [comment]
Solved, The right hand expression div_value | (int_part << 8) | frac_part seems wrong.

**Comment by lurch** [comment]
This is probably something that you should ask about at https://github.com/orgs/micropython/discussions rather than in this repo.

**Comment by leezisheng** [comment]
done,expression` div_value | (int_part << 8) | frac_part `change to ` (int_part << 8) | frac_part`.

**Comment by lurch** [comment]
For anybody else finding this issue in future: please see https://github.com/orgs/micropython/discussions/15816
